app = "addddsen-winchenzab"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder-jammy-base"

# Sadece bu kısmı tutuyoruz, ağ ayarlarını siliyoruz
[processes]
  app = "python main.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
