app = "addddsen"
primary_region = "ams"

[build]
# builder:base yerine güncel Jammy base imajını kullanıyoruz
builder = "paketobuildpacks/builder-jammy-base"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
